name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up gradle caches
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-padconnect-${{ hashFiles(
           '**/*.gradle',
           '**/*.gradle.kts',
           '**/gradle-wrapper.properties',
           '**/gradle.properties',
           '**/settings.gradle',
           '**/settings.gradle.kts',
           '**/libs.versions.toml'
           ) }}
          restore-keys: |
            ${{ runner.os }}-padconnect-

      - name: Setup Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Keystore
        env:
          KEYSTORE_ENCODED: ${{ secrets.KEYSTORE }}
        run: |
          echo "$KEYSTORE_ENCODED" | base64 --decode > ${{ github.workspace }}/app/ks.jks

      - name: Build
        env:
          KEYSTORE_PATH: "ks.jks"
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: Android APK
          path: |
            ./app/build/outputs/apk/release/app-release.apk
